#!/bin/bash
docker build -t hamelsmu/wandb .

INPUT_PROJECT_NAME="hamelsmu/test-wandb-action"
GITHUB_WORKSPACE="/data"
GITHUB_SHA="testsha1234"
INPUT_DISPLAY_METRICS="['acc', 'loss', 'val_acc', 'val_loss']"
INPUT_DISPLAY_CONFIG_VARS="['secondary_sha']"
INPUT_BASELINE_TAGS="['baseline']"
INPUT_DEBUG="y"


docker run \
-e INPUT_FILTER_GITHUB_SHA=$GITHUB_SHA \
-e INPUT_FILTER_SECONDARY_SHA="" \
-e INPUT_PROJECT_NAME=$INPUT_PROJECT_NAME \
-e INPUT_BASELINE_TAGS="$INPUT_BASELINE_TAGS" \
-e INPUT_DISPLAY_METRICS="$INPUT_DISPLAY_METRICS" \
-e INPUT_DISPLAY_CONFIG_VARS="$INPUT_DISPLAY_CONFIG_VARS" \
-e WANDB_API_KEY=$INPUT_WANDB_API_KEY \
-e GITHUB_WORKSPACE=$GITHUB_WORKSPACE \
-e INPUT_DEBUG=$INPUT_DEBUG \
-v ${PWD}:/data/ \
hamelsmu/wandb